# permissions to do edit freshcontainermonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: freshcontainermonitor-editor-role
rules:
- apiGroups:
  - infrastructure.fresh-container-operator.suse.com
  resources:
  - freshcontainermonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.fresh-container-operator.suse.com
  resources:
  - freshcontainermonitors/status
  verbs:
  - get
  - patch
  - update
